name = "glassbox-backend-testing"
main = "src/index.js"
compatibility_date = "2026-04-02"

[[d1_databases]]
binding = "DB"
database_name = "glassbox-db"
database_id = "3b6516d5-e64b-4d5f-8b79-1d5fb011374a"

[[d1_databases]]
binding = "TELEMETRY_DB"
database_name = "glassbox-telemetry"
database_id = "3ac73a2f-1a38-4ce1-b73b-6b754939779b"

[[kv_namespaces]]
binding = "GLASSBOX_KV"
id = "972c1fbb2a47474b8648a1efd777388e"

[triggers]
crons = ["*/15 * * * *", "0 * * * *"]

[observability]
[observability.logs]
enabled = true
invocation_logs = false

[[analytics_engine_datasets]]
binding = "GLASSBOX_LOGS"
dataset = "glassbox_logs"
